### PR TITLE
easy pr

### PR DESCRIPTION
**Pull request by nlin-work**
requesting pull request

Checklist and meta-data:
jira_ticket_url: 
Inspection_review: yes
Tests_defined: yes
Documentation_updated: yes

### CODE REVIEW

**Comment by nlin-work** [comment]
@nlin-rw Please review

**Comment by nlin-rw** [comment]
Review failed. @nlin-rightware

**Comment by nlin-work** [comment]
Please review again @nlin-rw

**Comment by nlin-rw** [comment]
Review passed. @nlin-rightware

**Pull request merged**
